### ISSUE TITLE
Switch builder methods from Duration to FiniteDuration

### ISSUE THREAD

**Issue by sjoerdmulder** [blemale/scaffeine#102]
First of all great wrapper!

I was using some of the methods like `refreshAfterWrite` and `expireAfter` and for testing (and since it should expire for a specific case) added `Duration.Inf` as argument. 

But this results always in the following error:

```
toNanos not allowed on infinite Durations
java.lang.IllegalArgumentException: toNanos not allowed on infinite Durations
	at scala.concurrent.duration.Duration$Infinite.fail(Duration.scala:217)
	at scala.concurrent.duration.Duration$Infinite.toNanos(Duration.scala:220)
```

Since it's not allowed, it might be better to make the API more specific and use `FiniteDuration` or allow it and set it then to Long.maxValue as suggested by the Caffeine project.

If you want i can make a PR if times allows it from my side :)

**Comment by blemale** [comment]
Hi Sjoerd! 
Thanks for creating this issue. Indeed the current behavior is not optimal. In a fist step I will go with the Caffeine behavior to not break the public API.
If you have time to open a PR it would be wonderful. :blush:

**Comment by blemale** [comment]
Hi Sjoerd! 
Thanks for creating this issue. Indeed the current behavior is not optimal. In a fist step I will go with the Caffeine behavior to not break the public API.
If you have time to open a PR it would be wonderful. :blush:

**Comment by blemale** [comment]
Hi Sjoerd! 
Thanks for creating this issue. Indeed the current behavior is not optimal. In a fist step I will go with the Caffeine behavior to not break the public API.
If you have time to open a PR it would be wonderful. :blush:

**Comment by ben-manes** [comment]
FYI, Caffeine allows setting with a java.time.Duration and saturates to a min/max long of nanos. You would be consistent if you matched that behavior.

**Comment by sjoerdmulder** [comment]
@blemale I do agree that we should not break public API, but changing it to `FiniteDuration` will not break it since it's a subclass of `Duration`. (Yes if someone would use `Infinite` it will now break at compile time but that was broken anyway at runtime)

Second `FiniteDuration` better matches `java.time.Duration` of Caffeine allowing to use the JavaConversions for it.

@ben-manes Thanks for the heads-up. This routine is used by Scaffeine in the PR coming up
