### ISSUE TITLE
2.12 build

### ISSUE THREAD

**Issue by tomasherman** [blemale/scaffeine#12]
Hey there,

is there any chance of having a 2.12 build? I would really appreciate that.

Thanks a lot, 
TH

**Comment by blemale** [comment]
Hi Tomas!

You already have 2.12 builds on Sonatype's snapshots repository, see https://oss.sonatype.org/content/repositories/snapshots/com/github/blemale/.

If you want I can release a `2.0.0-M2` version to make 2.12 builds available on Maven central.

WDYT ?

**Comment by blemale** [comment]
FYI here are the two PR which have added the 2.12 support:
* https://github.com/blemale/scaffeine/pull/9
* https://github.com/blemale/scaffeine/pull/10

**Comment by tomasherman** [comment]
No stress, we switched to plain caffeine for now to move on with transition to 2.12. When 2.0 is ready, we will probably move back to scaffeine. Thanks for all the effort :)

**Comment by blemale** [comment]
I have just released the 2.0.0 with 2.12 build, see https://oss.sonatype.org/content/repositories/releases/com/github/blemale/scaffeine_2.12/2.0.0/. It should be available on maven central soon.
