### ISSUE TITLE
Can be factory method typed?

### ISSUE THREAD

**Issue by hsn10** [blemale/scaffeine#132]
Is possible to make typed api something like

Object Scaffeine
  def apply[[K,V]](): Scaffeine[K, V] = ?

**Comment by blemale** [comment]
Hi @hsn10 ! Sorry to not reach you back sooner. What would be the use case to have typed factory method?

**Comment by hsn10** [comment]
It’s not needed, it constructs typed cache without it. I just had to use java.lang types and not Scala anyval.

**Comment by hsn10** [comment]
That can be prevented by adding type bounds to K, V - needs to be AnyRef
