### ISSUE TITLE
ExecutionContext for AsyncCache

### ISSUE THREAD

**Issue by renevangsgaardjp** [blemale/scaffeine#139]
I have read issue 6 https://github.com/blemale/scaffeine/issues/6

I am wondering why `AsyncLoadingCache.buildAsyncFuture()` doesn't use a loader of type `loader: (K1, scala.concurrent.ExecutionContext) => Future[V1]`.

`AsyncCacheLoaderAdapter` could convert the incoming `java.util.concurrent.Executor` to `ExecutionContext`.

The Future based loader I specify needs an ExecutionContext, and it should preferably come from the cache.

What do you think? 

Should I just construct the cache with the same ExecutionContext I use for the loader function?

**Comment by blemale** [comment]
Hi @renevangsgaardjp !

I think you should indeed construct the cache with the same ExecutionContext that you use for the loader function if you want to use the same for both. But this requirement depends on the use case so I'm not inclined into adding an ExecutionContext into the loader function.

**Comment by renevangsgaardjp** [comment]
Adding ExeuctionContext (preferably as implicit parameter) to the loader function would make it mirror Caffeine a bit more. And in case I do not construct the cache with an ExecutionContext, the cache constructs its own, and I would assume that the cache would use it all over, also in the loader function.

Feel free to close this issue, as I am fine with the solution of constructing the cache with the ExecutionContext I use for the loader function. And thank you for wrapping Caffeine in a nice Scala package.
