### ISSUE TITLE
Can I use JSR-107 Annotations with Scaffeine?

### ISSUE THREAD

**Issue by charlesxucheng** [blemale/scaffeine#17]
Hi. Is it possible to use annotations like @CacheResult if I use Scaffeine? Can you give some examples on how to do it? Thanks.

**Comment by blemale** [comment]
Hi! Sorry but scaffeine doesn't support JSR-107 however caffeine, the java library wrapped by scaffeine, support it: https://github.com/ben-manes/caffeine/wiki/JCache. So I would advise you to use directly caffeine.

**Comment by charlesxucheng** [comment]
Ok thanks.
