### ISSUE TITLE
Expiration API feedback

### ISSUE THREAD

**Issue by ben-manes** [blemale/scaffeine#18]
I have the foundation in place to support variable expiration. I'm hoping to work on the integration and expose it over the next few weeks. It would be nice to hear your feedback. The implementation uses a [TimerWheel](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/TimerWheel.java), which is an O(1) alternative to a O(lg n) priority queue.

See the [full API](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Expiry.java) for JavaDoc. In short it is,
```java
interface Expiry<K, V> {
  long expireAfterCreate(K key, V value, long currentTime);
  long expireAfterUpdate(K key, V value, long currentTime, long currentDuration);
  long expireAfterRead(K key, V value, long currentTime, long currentDuration);
}
```

The intent is to avoid allocations by using primitives, so it is slightly less friendly by using nanos instead of `Duration` objects. Its too bad value types are still a long ways off, so performance concerns leaks into the API. The `currentDuration` is available so that users can indicate no change and no expiration is modeled as returning a large duration (e.g. `Long.MAX_VALUE`).

How would you model this and make it idiomatic in Scala?

**Comment by blemale** [comment]
Sorry for the late answer, I haven't had the time to go deep into the new interface, but I'm not sure to understand how it will be used by the end user and so if it need to be wrapped by scaffeine.

However naively I would expose something like:
```scala
 trait Expiry[K, V] {
  def expireAfterCreate(key: K, value: V, currentTime: Instant): Long
  def expireAfterUpdate(key: K, value: V, currentTime: Instant, currentDuration: Duration): Long
  def expireAfterRead(key: K, value: V, currentTime: Instant, currentDuration: Duration): Long
}
```
Indeed in this wrapper is already doing additional allocations and avoid allocation is not really a priority in scala when you are manipulate immutable collections and so on.

**Comment by ben-manes** [comment]
I think being GC hygienic is important for Caffeine, but less so for Scaffeine where convenience trumps allocations. That way users can optimize by going lower-level if necessary.

An example usage would be Google Maps geocoding. In that case the client may cache the result for up to 30 days, as longer is a violation of the license. Therefore the client might store the results in the database and the cache, and periodically purge stale database records. The CacheLoader would query the database with a `creation_date` filter and, if not found, query Google's API and persist it. The local cache might hold an entry that expires in 30 days or 1 hour, depending on the results. That could be modeled using,

```java
class GelocationExpiry implements Expiry<Address, Geolocation> {
  public long expireAfterCreate(Address address, GeolocationRecord geolocation, long currentTime) {
    return currentTime - geolocation.getCreationDate().getNanos(); // java.time.Instant
  }
  public long expireAfterUpdate(K key, V value, long currentTime, long currentDuration) {
    return currentDuration; // Assume never updated, always read-through
  }
  public long expireAfterRead(K key, V value, long currentTime, long currentDuration) {
    return currentDuration;
  }
}
```

A friendlier `java.time` based API would require allocating for the `currentTime`, the `currentDuration` param, and possibly the result. That would result in allocations on every read `expireAfterRead`, even if unused. Due to escape analysis it might be stack allocated and not occur, but until Value Types land we can't be sure. By using a primitive we can force stack allocation and make the cost negligible.

From an API perspective, a functional builder would be nice a nice way to construct an instance of the interface. For example `Expiry.expiringAfterWrite((...) -> {...})`, but Java lacks a rich set of types and adding one-offs seems a little ugly. Scala's `FunctionX` would make that an option if you find the interface verbose.

**Comment by blemale** [comment]
Yes I totally agree that caffeine should be gc hygienic and I find this interface pretty neat.

Moreover I don't hide the underlying instance of caffeine cache in scaffeine to let the user going lower level if the additional cost of the wrapper is not suitable for one of its use cases. 

And thanks for the `Expiry.expiringAfterWrite((...) -> {...})` idea, it will let me optimized the non overridden methods of the interface.

**Comment by ben-manes** [comment]
Closing since the core implementation is done, but some work is still needed (more tests, jcache, etc). I'll ping you when 2.5 is released, which might be in a week or two (I have been a bit slow).

**Comment by ben-manes** [comment]
Released
