### ISSUE TITLE
AsyncLoadingCache .get does not wrap exceptions in Future

### ISSUE THREAD

**Issue by ryanb93** [blemale/scaffeine#26]
When using the AsyncLoadingCache and using `.get()`it calls `underlying.get(key).toScala`. The underlying `.get()` call can fail and throw an exception for instance when the update method can not connect to an external service to fetch the new data.

This results in needing to wrap each call to the AsyncLoadingCache `.get()` method in a `Try` to handle the possibility it will fail. As the return type is `Future[T]` we would expect no exceptions to be thrown from this code, but instead handle it as a failed `Future`.

    Try(cache.get(item)).recover {
      case ex: Exception => Future.failed(ex)
     }.get

This is not ideal, and would be nice to have this behaviour built into Scaffeine itself. 

https://github.com/blemale/scaffeine/blob/0f3df2a3f1a5152a038542bf829da7e921ffc777/src/main/scala/com/github/blemale/scaffeine/AsyncLoadingCache.scala#L41

**Comment by ben-manes** [comment]
The Java version is,

```java
/**
 * ...
 * 
 * @param key key with which the specified value is to be associated
 * @param mappingFunction the function to asynchronously compute a value
 * @return the current (existing or computed) future value associated with the specified key
 * @throws NullPointerException if the specified key or mappingFunction is null
 */
@Nonnull
CompletableFuture<V> get(@Nonnull K key,
    @Nonnull Function<? super K, ? extends V> mappingFunction);
```

Shouldn't that mean the only exception would be an NPE and the rest would be encapsulated into the future? Technically a `RejectedExecutionException` could be thrown when submitting to the executor if reconfigured away from `ForkJoinPool`. Is this a Scaffeine conversion issue or a Caffeine encapsulation problem?

**Comment by ryanb93** [comment]
Sorry, I confused two separate issues in our current code (using Guava cache) and our new code using Scaffeine.

`com.google.common.util.concurrent.UncheckedExecutionException: java.lang.reflect.UndeclaredThrowableException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2207)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875)`

This is a non-issue in Scaffeine :)
