### ISSUE TITLE
Caffeine 2.7

### ISSUE THREAD

**Issue by ben-manes** [blemale/scaffeine#42]
The latest release adds `AsyncCache`, split off from `AsyncLoadingCache`, to provide a manual version. This also includes an async `asMap()` view.

**Comment by blemale** [comment]
I will leave the async `asMap()` view out for now as I'm not sure how to implement it correctly if I want the following signature `def asMap(): concurrent.Map[K, scala.concurrent.Future[V]]`. I have opened #44 to track that.

**Comment by ben-manes** [comment]
Thanks!
