### ISSUE TITLE
getIfPresent why mapping to Some instead of wrapping?

### ISSUE THREAD

**Issue by wobu** [blemale/scaffeine#5]
Hey,

i suppose wrapping the future in `getIfPresent` with `Some(future)` would be better than mapping the result in Some.

I have following use case:
I want to check if a key is present in the cache. The only way i found was using the method `getIfPresent`.
When matching the Future against None everything is fine, cause this will returned immediatley. But in case it exists, the code has to wait until the Future initialized to get the Some value.

In my proposed way this situation would be immediatley at hand.

Feel free to correct me if i am wrong with my assumption :)

EDIT:
forgot to mention that i am using `AsyncLoadingCache`

**Comment by blemale** [comment]
You're right, the semantics of this method is not right regarding the one in Caffeine.

I want to change the signature to return an `Option[Future]` for some time but didn't did it as it is a breaking change. But if some people like you are bothered by it, I think it worth it to change the signature.

**Comment by wobu** [comment]
I just did some tests on this implementation and this caught my eye immediatley.

Currently i am not using in production or any comparable.
So don't be on a rush, take your time :)

**Comment by ben-manes** [comment]
@wobu In addition to @blemale's fix in 1.3, the alternative is a few hops away in the `Map` view. A `getIfPresent` records a hit and resets expireAfterAccess for that entry, whereas a `containsKey` does not. The hops have no cost and a trade-off to keep the interfaces small.

```scala
cache.synchronous.asMap.contains(key)
```

Thanks @blemale for this library and the maintenance work.

**Comment by blemale** [comment]
Fixed by 980f3f727dbb3a5c20356b42708f0c1c5c241437.
