### ISSUE TITLE
Redundant implicit ExecutionContext parameters in AsyncLoadingCache

### ISSUE THREAD

**Issue by albel727** [blemale/scaffeine#6]
`AsyncLoadingCache.get()`, `getFuture()`, and probably others do **NOT** need or use an ExecutionContext, yet they demand it as an implicit parameter, so now one has to provide/import some ExecutionContext at every calling site for no reason at all, which is nonfatal, but annoying.

I imagine you added this parameter because in other methods, e.g. `getAll()`, you used `Future.map()`, which actually demands an ExecutionContext, and then you just slapped it on everywhere else for good measure, which is understandable.

The unused parameters better be removed, but as some users may have already specified the parameter explicitly, if you don't want to break things for them, it might be better to specify a default value for the parameter instead, e.g. `null`.

But then, even `map()`s which actually make use of ExecutionContext are just an **implementation detail** of your library. Just a way you post-convert results that came from java Futures. The sanest thing to do here would be not to demand an ExecutionContext from user, but either of:

1.  Use an ExecutionContext derived from the Executor that the user specified during cache construction with the `Caffeine.executor()` method.
2. Better still, execute your post-conversions in the same thread as the original computations, since they're logically a part of them. 

For option 1 you can just obtain the user-defined executor from the cache and convert it with `ExecutionContext.fromExecutor()`.

But I like option 2 the most. The user has already expressed their will with regard to which thread the computations should run on by specifying (or leaving the default) Executor during cache construction. Jumping through additional threads and rescheduling hoops just so that a `toScala` executes on a java collection is suboptimal, imo. 

It can be implemented with a special executor. Scala's Futures actually use a class like that internally.

```scala
import java.util.concurrent.Executor
import scala.concurrent.ExecutionContext

class CurrentThreadExecutor extends Executor {
  override def execute(r : Runnable) {
    r.run()
  }
}

object CurrentThreadExecutor {
  implicit val instance = ExecutionContext.fromExecutor(new CurrentThreadExecutor)
}
```

All that is left is to supply the `instance` in all wrapper methods.

Whichever option you choose, the resulting EC would preferably go as default value for the implicit parameter, if you don't want to break existing users and keep the flexibility of allowing users to reschedule post-conversions to other threads, though I fail to see a use for it.

**Comment by blemale** [comment]
Thanks for this detailed issue, I agree with you, with more hindsight this mandatory `ExecutionContext` could be annoying. I like your second solution with a direct executor.

As I have to release a non backward compatible version due to 980f3f727dbb3a5c20356b42708f0c1c5c241437, I will also ship this improvement and remove totally the implicit `ExecutionContext`.

**Comment by albel727** [comment]
Looks great! Cheers.
