### ISSUE TITLE
Is % compile necessary for sbt example in README?

### ISSUE THREAD

**Issue by wuservices** [blemale/scaffeine#80]
The README has this example for including scaffeine with sbt:

```
"com.github.blemale" %% "scaffeine" % "3.1.0" % "compile"
```

Sorry this may be a silly question, but I was wondering what `% "compile"` did here. Does it do anything different than leaving it out?

**Comment by blemale** [comment]
Hello @wuservices !

You can leave it out as the `compile` configuration is the default one in SBT. However if you need the dependency only for your test, you will need to add the `% "test"` at the end.

If you need more details on how dependencies work in SBT you can look at the official documentation:
* https://www.scala-sbt.org/1.x/docs/Library-Dependencies.html
* https://www.scala-sbt.org/1.x/docs/Library-Management.html
